### ISSUE TITLE
Unable to create ImageAnnotatorClient

### ISSUE THREAD

**Issue by dnwarnock** [googleapis/java-vision#820]
#### Environment details

1. google-cloud-vision
2. macOS Mojave 10.14.6
3. Java version: 11
4.  version(s):
<dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-vision</artifactId>
        <version>2.0.19</version>
 </dependency>

#### Steps to reproduce

I'm trying to create an ImageAnnotatorClient within a gRPC based spring boot service. Unfortunately, on creation I'm encountering the error below. Is there some configuration I'm missing when setting up the vision client? Could there be dependency conflicts between the gRPC libraries used by my service and those used by the vision sdk? 

I would assume that [this](https://github.com/grpc/grpc-java/blob/042f9879d4c36aa4a4b04937c8f2e5775b851342/core/src/main/java/io/grpc/internal/GrpcUtil.java#L196) value should get picked up?

#### Code example

```java
try (ImageAnnotatorClient client = ImageAnnotatorClient.create()) {
...
}
```

#### Stack trace
```
Exception in thread "grpc-default-executor-0" java.lang.NoSuchFieldError: maxInboundMessageSize
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize(NettyChannelBuilder.java:520)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize(NettyChannelBuilder.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:386)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1900(InstantiatingGrpcChannelProvider.java:85)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:246)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:149)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:96)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:256)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:234)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:241)
	at com.google.cloud.vision.v1.stub.GrpcImageAnnotatorStub.create(GrpcImageAnnotatorStub.java:115)
	at com.google.cloud.vision.v1.stub.ImageAnnotatorStubSettings.createStub(ImageAnnotatorStubSettings.java:156)
	at com.google.cloud.vision.v1.ImageAnnotatorClient.<init>(ImageAnnotatorClient.java:131)
	at com.google.cloud.vision.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:112)
	at com.google.cloud.vision.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:103)
```

#### Maven dependencies:
```xml
<properties>
    <java.version>11</java.version>
    <micrometer.version>1.6.1</micrometer.version>
    <protoc.version>3.19.3</protoc.version>
    <io.grpc.version>1.44.0</io.grpc.version>
    <springfox-swagger.version>3.0.0</springfox-swagger.version>
    <lomboc.version>1.18.10</lomboc.version>
    <native-libs.dir>native-libs</native-libs.dir>
    <aws.java.sdk.version>1.12.156</aws.java.sdk.version>
  </properties>

<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger-ui</artifactId>
        <version>${springfox-swagger.version}</version>
      </dependency>
      <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-boot-starter</artifactId>
        <version>${springfox-swagger.version}</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-jetty</artifactId>
        <version>2.6.3</version>
      </dependency>
      <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-core</artifactId>
        <version>${micrometer.version}</version>
      </dependency>



      <!-- Google protobuf and gRPC dependencies -->
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protobuf-java</artifactId>
        <version>${protoc.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protobuf-java-util</artifactId>
        <version>${protoc.version}</version>
      </dependency>
      <dependency>
        <groupId>com.googlecode.protobuf-java-format</groupId>
        <artifactId>protobuf-java-format</artifactId>
        <version>1.4</version>
      </dependency>
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-testing</artifactId>
        <version>${io.grpc.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
        <version>4.9.3</version>
      </dependency>

      <!-- AWS Resources -->
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-core</artifactId>
        <version>${aws.java.sdk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-s3</artifactId>
        <version>${aws.java.sdk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-dynamodb</artifactId>
        <version>${aws.java.sdk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-secretsmanager</artifactId>
        <version>${aws.java.sdk.version}</version>
      </dependency>

      <!-- Web Entity Retrieval Resources -->
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-vision</artifactId>
        <version>2.0.19</version>
      </dependency>
      <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-jpeg</artifactId>
        <version>3.6.2</version>
      </dependency>
    </dependencies>
```

**Comment by galz10** [comment]
Hi @dnwarnock please use these versions bellow

```    
<dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.19.4</version>
</dependency>
<dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
      <version>3.19.4</version>
</dependency>
<dependency>
      <groupId>com.googlecode.protobuf-java-format</groupId>
      <artifactId>protobuf-java-format</artifactId>
      <version>1.4</version>
</dependency>
<dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-testing</artifactId>
      <version>1.44.0</version>
      <scope>test</scope>
 </dependency>
 ```

**Comment by dnwarnock** [comment]
Hello @galz10! Thanks the response. I changed my versions for `protobuf-java` and `protobuf-java-util` from `3.19.3` to `3.19.4` and the same error persists. To unblock myself I'll attempt to access the vision apis over rest, but using the gRPC sdk would be preferable.

**Comment by dnwarnock** [comment]
I tried running https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-util/google-cloud-compat-checker in my env and received the following:

Result: FAIL
  Your environment is not supported by Forked Tomcat Native.
  See http://netty.io/wiki/forked-tomcat-native.html for details.
  This means that you won't be able to use grpc-based APIs, but
  http1-based APIs should still work.

with stacktrace:

  [FAIL] Open SSL is NOT available
         Open SSL Unavailability cause:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:107)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
	at com.google.cloud.compatchecker.GoogleCloudCompatChecker.check(GoogleCloudCompatChecker.java:58)
	at com.google.cloud.compatchecker.GoogleCloudCompatChecker.main(GoogleCloudCompatChecker.java:47)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dnwarnock** [comment]
I'm not 100% why this fixed this issue but manually adding:

`
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.0.Final</version>
</dependency>
`

resolved this issue

**Comment by galz10** [comment]
Hi @dnwarnock thank you for keeping me updated, as this issue is resolved i'll close this issue but i'll take a look at why this helped. If this issue shows up again feel free to reopen this issue.
